### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by DMNerd**
Hello. I have translated your app to Czech language. This is the first time I used the localisation features in xcode so please bear with me if I did anything wrong or forgot to do something etc. I am submitting as is and will repair stuff as needed. 

Thank you for this cool opensource project :)

### CODE REVIEW

**Comment by DMNerd** [comment]
BTW I do not understand what Main.strings and if it needs translation as well. If I am given explanation I will translate it ASAP :)

**Comment by gao-sun** [comment]
thank you for contributing to the project! I think Main.strings are generated by Xcode which includes some general phrases. As we are not using them in eul, you can delete it directly along with the placeholder in `eul.xcodeproj/project.pbxproj`. cheers!

**Review by CZGlomerulus — DISMISSED** [review]

**Comment by DMNerd** [comment]
Thanks! I removed the Main.string keeping only the changes to the translation itself. If anything else is needed HMU or you can Merge :)

Thanks!

**Comment by DMNerd** [comment]
Also removed the eul.xcodeproj/project.pbxproj edits you mentioned. Sorry, Xcode is kinda confusing at first :)

**Comment by gao-sun** [comment]
thanks! for me Xcode is also really hard to get started.

btw, would you mind to clear build error before merging? I think you just need to remove the unused file in `pbxproj`

**Comment by DMNerd** [comment]
Yea sure. I will manage it when I wake up :)

**Comment by DMNerd** [comment]
I actually fixed it right now. Who needs sleep anyway. Sorry for my clumsy PR. Did not mean to cause any inconvenience

**Comment by DMNerd** [comment]
Merged just to make sure twice

**Comment by jevonmao** [comment]
I fixed the merge conflict.

**Comment by DMNerd** [comment]
> I fixed the merge conflict so I merged the master in again.

Thank you very much!

**Comment by jevonmao** [comment]
@DMNerd I noticed a minor issue. The language selection for Czech shows as "language.cs" instead of a readable language name. You might want to fix that typo to "language.cz"?

**Comment by jevonmao** [comment]
Should be fixed. Everything looks good now.

**Review by jevonmao — APPROVED** [review]

**Comment by gao-sun** [comment]
thanks guys

**Pull request merged**
